### ISSUE TITLE
System.NullReferenceException in Activity

### ISSUE THREAD

**Issue by qdraw** [qdraw/tabletop#9]
There is in the System.NullReferenceException in https://github.com/qdraw/tabletop/pull/8 

```
2|tabletop  | System.NullReferenceException: Object reference not set to an instance of an object.
2|tabletop  |    at tabletop.Services.ActivityUpdate.IsAvailable() in D:\a\1\s\tabletop\tabletop\Services\ActivityUpdate.cs:line 58
2|tabletop  |    at lambda_method(Closure , Object , Object[] )
2|tabletop  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2|tabletop  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
2|tabletop  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2|tabletop  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
```

**Comment by qdraw** [comment]
fixed in b3b0575759c6830b3f8355d27df9c3038c464bbc
